apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: armswideopen
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - monitoring.yaml
  - backup-cronjob.yaml
  - secret-provider-class.yaml
